name: Pull Request

on: pull_request

jobs:
    ubuntu-build:
        name: Build on Ubuntu
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: '17.0.10'

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
                
            -   name: Build the Package
                env:
                    packageUser: ${{ github.actor }}
                    packagePAT: ${{ secrets.GITHUB_TOKEN }}
                    CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
                run: ./gradlew build --no-daemon --scan

            -   name: Generate Codecov Report
                uses: codecov/codecov-action@v2

    windows-build:
        name: Build on Windows
        runs-on: windows-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: '17.0.10'

            -   name: Build the Project
                env:
                    packageUser: ${{ github.actor }}
                    packagePAT: ${{ secrets.GITHUB_TOKEN }}
                    CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
                    JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
                run: ./gradlew.bat build --no-daemon --scan
